### PR TITLE
Make Cairo dep optional?

### PR DESCRIPTION
**Pull request by NHDaly**
I'm not sure if this makes sense to you, but I thought that it would be nice to
remove the Cairo dependency. It's only there to enable adding an SDL wrapper or
extension (I'm not sure which) if you want to use Cairo and SDL together,
right? But it seems unecessary to pull in Cairo to a user if they just want to use SDL.

What do you think?

If you agree, i pushed up a commit which I think does that: it just checks that
Cairo is installed before defining the Cairo-specific code. Does that seem
like a reasonable approach?

### CODE REVIEW

**Comment by jonathanBieler** [comment]
Removing Cairo is fine for me. I added it initially because I wanted to use it to draw, but I agree it shouldn't be in this package (it's mixing different concerns). 

So I would remove it altogether (conditional dependency isn't so nice) and I can put the glueing code in another package that depend on both Cairo and SDL when I need it.

**Comment by NHDaly** [comment]
Okay, yeah, i've just removed it then! :) That makes sense to me!

**Comment by jonathanBieler** [comment]
You still need to remove the `include(joinpath("..","src","examples","example1_cairo.jl"))` part in .runtests.jl and it should work.

**Comment by jonathanBieler** [comment]
I think it's better to test the example, so we know it actually works.

**Comment by NHDaly** [comment]
👍 Thanks for fixing that and merging it for me! :) Sorry i never got around to it.

**Comment by NHDaly** [comment]
And actually, would it be possible to cut another version release of this package so that the Cairo dependency isn't needed to build this package through Pkg?

I'm working on fixing Cairo so that it won't be breaking Travis build status, but in the meantime, broken Cairo means my builds are all broken, and I wanted to use SDL.jl in a unit-test for ApplicationBuilder. :(

**Comment by jonathanBieler** [comment]
I'll make a release yes, but all tests are failing right now, so I need to fix that first.

Very nice talk at Juliacon btw.

**Comment by NHDaly** [comment]
😄 Awesome thanks for taking care of it! I appreciate it!! :)


> Very nice talk at Juliacon btw.

😅 Thanks! It was lots of fun, if also very terrifying. I'm glad it's over... haha. Thanks again for all your help with Paddle Battle, which was the star of the show!! :)

**Pull request merged**
