### PR TITLE
Fix deprecations (for Julia v1.0) 

### PR DESCRIPTION
**Pull request by jonathanBieler**
This is @dalum branch with some modifications

### CODE REVIEW

**Comment by jonathanBieler** [comment]
There's still one issue on windows but I think it's an upstream problem with BinDeps.

**Comment by NHDaly** [comment]
Hmm, the appveyor failure looks like it can't find `libSDL2_ttf` for some reason?:
https://ci.appveyor.com/project/jonathanBieler/sdl2-jl/build/1.0.58/job/ctmv2s4n9fj6ghsv

```julia
Init+Quit: Error During Test at C:\projects\sdl2-jl\test\lib\SDL_ttf.jl:10
  Test threw exception
  Expression: 0 == SDL2.TTF_Init()
  UndefVarError: libSDL2_ttf not defined
  Stacktrace:
   [1] TTF_Init() at C:\projects\sdl2-jl\src\lib\SDL_ttf.jl:14
   [2] macro expansion at C:\projects\sdl2-jl\test\lib\SDL_ttf.jl:10 [inlined]
   [3] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
```

Hard to say why that would work on 0.7 but not 1.0...

Here's the build error message at the top:
```
  Building SimpleDirectMediaLayer → `C:\projects\sdl2-jl\deps\build.log`
 Resolving package versions...
┌ Error: Error building `SimpleDirectMediaLayer`: 
│ 
│ 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
│ 
│ Scanning the drive for archives:
│ 1 file, 494710 bytes (484 KiB)
│ 
│ Extracting archive: C:\projects\sdl2-jl\deps\downloads\SDL2-2.0.7-win32-x64.zip
│ --
│ Path = C:\projects\sdl2-jl\deps\downloads\SDL2-2.0.7-win32-x64.zip
│ Type = zip
│ Physical Size = 494710
│ 
│ Everything is Ok
│ 
│ Files: 2
│ Size:       1220529
│ Compressed: 494710
│ [ Info: Attempting to create directory C:\projects\sdl2-jl\deps\downloads
│ [ Info: Downloading file https://www.libsdl.org/release/SDL2-2.0.7-win32-x64.zip
│ [ Info: Done downloading file https://www.libsdl.org/release/SDL2-2.0.7-win32-x64.zip
│ [ Info: Attempting to create directory C:\projects\sdl2-jl\deps
│ [ Info: Directory C:\projects\sdl2-jl\deps already exists
│ ERROR: LoadError: UndefVarError: Libdl not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\appveyor\.julia\packages\BinDeps\Z6fwm\src\dependencies.jl:974
│  [2] top-level scope at C:\projects\sdl2-jl\deps\build.jl:31
│  [3] include at .\boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at .\loading.jl:1038
│  [5] include(::Module, ::String) at .\sysimg.jl:29
│  [6] include(::String) at .\client.jl:388
│  [7] top-level scope at none:0
│ in expression starting at C:\projects\sdl2-jl\deps\build.jl:28
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068
```

Oh actually, i bet it's this line:
https://github.com/jonathanBieler/SimpleDirectMediaLayer.jl/pull/25/files#diff-ed74277d7f2e98f12cf51e6b8be90705R41

I think we just need to add a `using Libdl` up top for that to work! :)

**Comment by NHDaly** [comment]
Haha sorry to stream-of-consciousness in that last post. I think we just need a `using Libdl` at the top of the `build.jl`.

**Comment by NHDaly** [comment]
I *think* i opened the PR correctly so that it will be merged into this PR?:
https://github.com/jonathanBieler/SimpleDirectMediaLayer.jl/pull/26

**Comment by jonathanBieler** [comment]
I think you did it correctly yes, but I've put the commit manually because I wasn't sure. I could give you access so you can push directly.

**Pull request merged**
