### PR TITLE
Fix deprecations (for Julia v1.0)

### PR DESCRIPTION
**Pull request by dalum**
These seem to be the required changes to get the package to work on 1.0.

### CODE REVIEW

**Comment by jonathanBieler** [comment]
Thanks! To get tests to pass I think we need to change this:

https://github.com/jonathanBieler/SimpleDirectMediaLayer.jl/blob/master/test/runtests.jl#L3

and also change the travis script a bit (I'll look into it).

**Comment by NHDaly** [comment]
I'm pretty sure the only things you'll need to change for travis are adding `julia: 0.7` and `julia 1.0` as separate targets, and changing the coverage line:
https://github.com/jonathanBieler/SimpleDirectMediaLayer.jl/blob/master/.travis.yml#L34

to call `using Pkg` for v0.7+:
```julia
    - julia -e '(if (VERSION >= v"0.7-") using Pkg; end); cd(Pkg.dir("SimpleDirectMediaLayer")); Pkg.add("SimpleDirectMediaLayer"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
```

**Comment by NHDaly** [comment]
And you can change `using Base.Test` to `using Compat; using Compat.Test`! :)

**Comment by jonathanBieler** [comment]
See #25

**Pull request closed without merging**
