### PR TITLE
Switch from BinDeps to BinaryProvider (BinDeps2)

### PR DESCRIPTION
**Pull request by NHDaly**
Closes https://github.com/jonathanBieler/SimpleDirectMediaLayer.jl/issues/38

Enable the work that @jonathanBieler did to set up BinaryBuilder/BinaryProvider for this repo! :)
This PR is just the last 1% of the work @jonathanBieler did to set everything up and get it working. Thanks for that! haha sorry to swoop-in at the last minute and create the PR; i was just excited to see it turned on. :)

Set up to pull the binaries from https://github.com/jonathanBieler/SDL2Builder by just downloading the generated `build.jl` and replacing it in this repo.

### CODE REVIEW

**Comment by jonathanBieler** [comment]
Thanks, I need to make builder for libSDL2_ttf and libSDL2_mixer before we can switch though, otherwise it's gonna break people code.

**Comment by NHDaly** [comment]
Ah, true, agreed. Good point! :)

I'd say you can probably just combine them all in one builder. I don't see much harm in that.
If you want you can open multiple separate builder repos as well, it just makes maintenance a bit harder of course.

**Comment by giordano** [comment]
Note that SDL2 is already in Yggdrasil and it has been built with X11 support, too: https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/SDL2/build_tarballs.jl.  We also have Wayland for Linux and we could add other dependencies, if needed.  I can produce a build.jl for this, if you want.

**Comment by jonathanBieler** [comment]
That would be great yes, I'm definitively not an expert at this (although I start to understand a bit how the system works).

**Comment by giordano** [comment]
I've opened a PR at https://github.com/NHDaly/SimpleDirectMediaLayer.jl/pull/5 against the branch of this PR

**Comment by NHDaly** [comment]
Woah, thanks @giordano! :)

Woahhh, reading about Yggdrasil, it sounds really crazy! Neat! Lol i have learned from google that it is an ancient norse tree? 😂

The BinaryBuilder stuff has changed a lot since I last looked. Thanks for pointing this out!

**Comment by jonathanBieler** [comment]
@NHDaly Have you seen this blog [post](https://github.com/JuliaLang/www.julialang.org/pull/417/files#diff-514f74c34d50677638b76f65d910ad17) ? seems pretty cool indeed.

Otherwise I think you need to merge the PR on your branch.

**Comment by aviks** [comment]
There are now jll packages for SDL2, SDL2_ttf, SDL2_image and SDL2_mixer. How do we want to proceed here? Make a 1.3+release with these changes? I'm not sure how easy it will be to port these jll packages to 1.0-1.2.

**Comment by giordano** [comment]
> I'm not sure how easy it will be to port these jll packages to 1.0-1.2.

In my experience, for libraries having many dependencies, using `BinaryProvider` is quite a pain.  I'm so glad JLL packages handle dependencies in a much simpler way.

**Comment by aviks** [comment]
This can now be closed.

**Pull request closed without merging**
